name: Deploy NG app

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write      # to deploy to Pages
      id-token: write  

    steps:
    - uses: actions/checkout@v4

    - name: Adding Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 22.19.0

    - name: Build
      run: |
        npm ci
        
    - name: Run lint
      run: |
        npm run lint
        
    - name: Build Angular app
      run: |
        npm run build -- --configuration production

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          folder: ./dist/hello-world/browser/
          branch: gh-pages
