name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Adding Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 22.19.0

    - name: Build
      run: |
        npm install
        npm run build

    - name: Deploy to gh pages
      run: |
        npx angular-cli-ghpages --dir=dist/HelloWorldDevOps
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GITHUBPAGES }}
